# Generated by Django 4.1.7 on 2023-03-15 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fed', models.DateField()),
                ('feeding_interval', models.IntegerField()),
                ('next_feeding', models.DateField()),
                ('snake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snakes.snake')),
            ],
        ),
    ]
