# Generated by Django 4.1.7 on 2023-03-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0003_alter_feeding_next_feeding_enclosure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enclosure',
            new_name='Cleaning',
        ),
    ]
