# Generated by Django 4.1.7 on 2023-03-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0003_breedingpair_is_paired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingpair',
            name='is_paired',
        ),
    ]
