# Generated by Django 4.1.7 on 2023-03-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0004_remove_breedingpair_is_paired'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='marked_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeding',
            name='marked_complete',
            field=models.BooleanField(default=False),
        ),
    ]
