# Generated by Django 4.1.7 on 2023-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0004_rename_enclosure_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='paired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='next_cleaning',
            field=models.DateField(blank=True, null=True),
        ),
    ]
