# Generated by Django 4.1.7 on 2023-03-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0005_snake_paired_alter_cleaning_next_cleaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_pairs_as_female', to='snakes.snake')),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_pairs_as_male', to='snakes.snake')),
            ],
        ),
    ]
