# Generated by Django 4.1.7 on 2023-03-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0005_cleaning_marked_complete_feeding_marked_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='last_fed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='next_feeding',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
