# Generated by Django 4.1.7 on 2023-03-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0006_alter_feeding_last_fed_alter_feeding_next_feeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='last_fed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='next_feeding',
            field=models.DateField(blank=True, null=True),
        ),
    ]
