# Generated by Django 4.1.7 on 2023-03-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0007_alter_feeding_last_fed_alter_feeding_next_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='is_up_to_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snake',
            name='needs_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snake',
            name='needs_feeding',
            field=models.BooleanField(default=False),
        ),
    ]
