# Generated by Django 4.1.7 on 2023-03-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0009_remove_snake_is_up_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingpair',
            name='female',
            field=models.ForeignKey(limit_choices_to={'gender': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_pairs_as_female', to='snakes.snake'),
        ),
        migrations.AlterField(
            model_name='breedingpair',
            name='male',
            field=models.ForeignKey(limit_choices_to={'gender': 'male'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_pairs_as_male', to='snakes.snake'),
        ),
    ]
