# Generated by Django 4.1.7 on 2023-03-25 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0010_alter_breedingpair_female_alter_breedingpair_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='paired',
        ),
        migrations.AddField(
            model_name='snake',
            name='female',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dams', to='snakes.snake'),
        ),
        migrations.AddField(
            model_name='snake',
            name='male',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sires', to='snakes.snake'),
        ),
    ]
