# Generated by Django 4.1.7 on 2023-03-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0011_remove_snake_paired_snake_female_snake_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='female',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='male',
        ),
        migrations.AddField(
            model_name='snake',
            name='paired',
            field=models.BooleanField(default=False),
        ),
    ]
