# Generated by Django 4.1.7 on 2023-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0012_remove_snake_female_remove_snake_male_snake_paired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='last_fed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='next_feeding',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
